mehmberportal/urls.py
from django.urls import path

from . import views
from .views import payment_history
from .views import unlock

app_name = 'mehmberportal'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('payment-history/', payment_history, name='payment_history'),
    path('unlock/', unlock, name='unlock'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

from api.views import auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/auth/', csrf_exempt(auth.create_authentication_request)),
    path('', include('mehmberportal.urls')),
]

mehmberportal/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.utils.translation import gettext_lazy as _


class Member(AbstractUser):
    groups = models.ManyToManyField(
        Group,
        verbose_name=_("groups"),
        blank=True,
        help_text=_(
            "The groups this user belongs to. A user will get all permissions "
            "granted to each of their groups."
        ),
        related_query_name="member",
        related_name="%(app_label)s_%(class)s_related",  # Add this line
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_("user permissions"),
        blank=True,
        help_text=_("Specific permissions for this user."),
        related_query_name="member",
        related_name="%(app_label)s_%(class)s_related",  # Add this line
    )

mehmberportal/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

mehmberportal/views.py
import datetime

import gnupg
import paho.mqtt.client as mqtt
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from mehmberprofile.models import PaymentHistory, MehmbershipHistory
from mehmberprofile.views import mehmbership_due, amount_due_string, is_active_member, mehmber_accessed_hackspace
from settings import SECRETS
from .forms import LoginForm


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('mehmberportal:dashboard')
    else:
        form = LoginForm()
    return render(request, 'conpan/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'conpan/dashboard.html')


def logout_view(request):
    logout(request)
    return redirect('mehmberportal:login')


@login_required
def payment_history(request):
    payments = PaymentHistory.objects.filter(user=request.user)
    membership_history = MehmbershipHistory.objects.filter(user=request.user).order_by('-start_date')
    return render(request, 'conpan/payment_history.html',
                  {'payments': payments, 'amount_due_str': amount_due_string(request),
                   'membership_history': membership_history})


def calc_payload_to_unlock():
    gpg = gnupg.GPG()  #  get at  https://gpg4win.org/
    #/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    #sudo apt-get install gnupg
    # regardless of OS, you'll need to run:    gpg --import ./door_pub_key.asc
    # gpg --edit-key FB6A37AAAFA7ACD7571AB220EE4EFDD43B4A8504
    # trust
    # 5
    # y
    # save
    key_data = SECRETS['door']['pubcert']
    import_result = gpg.import_keys(key_data)
    if import_result.count == 0:
        raise ValueError("Key import failed")

    salty_bastard = "friend"
    message = SECRETS['door']['psk'] + salty_bastard + str(datetime.datetime.now().microsecond)
    encrypted_data = gpg.encrypt(message, import_result.fingerprints[0])

    return encrypted_data.data


@login_required
def unlock(request):
    amount_due = mehmbership_due(request.user)
    active_member = is_active_member(request.user)
    membership_in_good_standing = amount_due <= (30 * 3) and active_member
    access_granted = membership_in_good_standing
    if access_granted:
        client = mqtt.Client()
        client.connect(SECRETS['mqtt']['host'], SECRETS['mqtt']['port'], 60)
        # TODO include private gpg key on door iot.  Decrypt/validate payload. store/invalidate timestamp as nonce on TF
        unlock = calc_payload_to_unlock()
        client.publish('meh/meh-api/door/access', payload=unlock,
                       qos=0, retain=False)
        mehmber_accessed_hackspace(request)

    return render(request, 'conpan/unlock.html', {'amount_due_str': amount_due_string(request), })

mehmberportal/templates/conpan/dashboard.html
{% extends 'base.html' %}

{% block content %}
<h2>Dashboard</h2>
<p>Welcome, {{ user.username }}!</p>


<a href="{% url 'mehmberportal:unlock' %}" class="btn btn-primary">Unlock Door</a>
<br/>
<br/>
<br/>
<br/>
<a href="{% url 'mehmberportal:logout' %}" class="btn btn-primary">Logout</a>
{% endblock %}

mehmberportal/templates/conpan/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

mehmberportal/templates/conpan/payment_history.html
{% extends "base.html" %}

{% block content %}
<table>
    <tr>
        <td colspan="2"><h2>Membership Amount Due:</h2></td>
        <td><h2>{{ amount_due_str }}</h2></td>
    </tr>
</table>

<h2>Payment History</h2>
<table>

    <thead>
    <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Amount</th>
    </tr>
    </thead>
    <tbody>
    {% for payment in payments %}
    <tr>
        <td>{{ payment.date }}</td>
        <td>{{ payment.description }}</td>
        <td>${{ payment.amount }}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="3">No payment history available.</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% if membership_history %}
<h2>Membership History</h2>
<table>
    <thead>
    <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Monthly Price</th>
    </tr>
    </thead>
    <tbody>
    {% for membership in membership_history %}
    <tr>
        <td>{{ membership.start_date }}</td>
        <td>{{ membership.end_date }}</td>
        <td>${{ membership.monthly_price }}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="3">No membership history available.</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

mehmberportal/templates/conpan/unlock.html
{% extends "base.html" %}

{% block content %}
<table>
    <tr>
        <td colspan="2"><h2>Membership Amount Due:</h2></td>
        <td><h2>{{ amount_due_str }}</h2></td>
    </tr>
</table>

<h2>Speak friend. And Enter!</h2>

{% endblock %}